# Generated by Django 2.1.7 on 2019-03-05 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={},
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(blank=True, choices=[('eng', 'English'), ('spa', 'Spanish')], default='eng', help_text='ISO 639.2 language', max_length=100),
        ),
    ]
